[package]
name = "codex-mcp-server"
version = { workspace = true }
edition = "2024"

[[bin]]
name = "codex-mcp-server"
path = "src/main.rs"

[lib]
name = "codex_mcp_server"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
codex-core = { path = "../core" }
mcp-types = { path = "../mcp-types" }
schemars = "0.8.22"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = { version = "0.1.41", features = ["log"] }

tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter", "json"] }
tokio = { version = "1", features = [
    "io-std",
    "macros",
    "process",
    "rt-multi-thread",
    "signal",
] }


anyhow = "1.0"


[dev-dependencies]
pretty_assertions = "1.4.1"

criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "my_server_benchmarks" 
harness = false
