[package]
edition = "2024"
name = "codex-login"
version = { workspace = true }

[lints]
workspace = true

[dependencies]
base64 = "0.22"
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.12", features = ["json", "blocking"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tempfile = "3"
thiserror = "2.0.12"
tokio = { version = "1", features = [
    "io-std",
    "macros",
    "process",
    "rt-multi-thread",
    "signal",
] }
tiny_http = "0.12"
sha2 = "0.10"
rand = "0.8"
urlencoding = "2.1"
webbrowser = "1.0"

[dev-dependencies]
pretty_assertions = "1.4.1"
tempfile = "3"

[[bin]]
name = "codex-login-server"
path = "src/bin/codex-login-server.rs"
