name: ci

on:
  pull_request: { branches: [main] }
  push: { branches: [main] }

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      NODE_OPTIONS: --max-old-space-size=4096
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # Run codex-cli/ tasks first because they are higher signal.

      - name: Install dependencies (codex-cli)
        working-directory: codex-cli
        run: npm ci

      - name: Check formatting (codex-cli)
        working-directory: codex-cli
        run: npm run format

      - name: Run tests (codex-cli)
        working-directory: codex-cli
        run: npm run test

      - name: Lint (codex-cli)
        working-directory: codex-cli
        run: |
          npm run lint -- \
            --rule "no-console:error" \
            --rule "no-debugger:error" \
            --max-warnings=-1

      - name: Type‑check (codex-cli)
        working-directory: codex-cli
        run: npm run typecheck

      - name: Build (codex-cli)
        working-directory: codex-cli
        run: npm run build

      # Run formatting checks in the root directory last.

      - name: Install dependencies (root)
        run: npm ci

      - name: Check formatting (root)
        run: npm run format

  update-nix-hash:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write  # Needed for push access
      pull-requests: write  # Needed for PR creation
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Need previous commit to check for changes
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@v8
      
      - name: Make script executable
        run: chmod +x "${GITHUB_WORKSPACE}/codex-cli/scripts/update-nix-hash.sh"
      
      - name: Update nix npm hash
        id: update-hash
        run: |
          OUTPUT=$(${GITHUB_WORKSPACE}/update-nix-hash.sh)
          echo "::set-output name=changed::$(echo $OUTPUT | grep -q "Hash updated" && echo "true" || echo "false")"
        env:
          GITHUB_ACTIONS: "true"
      
      - name: Create branch
        if: steps.update-hash.outputs.changed == 'true'
        run: |
          git checkout -b update-npm-hash-$(date +%Y%m%d%H%M%S)
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add flake.nix
          git commit -m "Update npm hash in flake.nix"
          git push --set-upstream origin HEAD
      
      - name: Create Pull Request
        if: steps.update-hash.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update npm hash in flake.nix
          title: Update npm hash in flake.nix
          body: |
            This PR updates the npm hash in flake.nix based on changes to the package-lock.json file.
            
            Automated PR created by GitHub Actions.
          branch: update-npm-hash-$(date +%Y%m%d%H%M%S)
          base: main
          draft: false
