name: Issue Labeler

on:
  issues:
    types:
#      - opened
      - labeled

jobs:
  gather-labels:
    name: Generate label suggestions
    if: ${{ github.event.action == 'opened' || (github.event.action == 'labeled' && github.event.label.name == 'codex-label') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      ISSUE_NUMBER: ${{ github.event.issue.number }}
      ISSUE_TITLE: ${{ github.event.issue.title }}
      ISSUE_BODY: ${{ github.event.issue.body }}
      REPO_FULL_NAME: ${{ github.repository }}
    outputs:
      codex_output: ${{ steps.codex.outputs.final_message }}
    steps:
      - uses: actions/checkout@v4

      - id: codex
        uses: openai/codex-action@main
        with:
          openai_api_key: ${{ secrets.CODEX_OPENAI_API_KEY }}
          prompt_file: .github/prompts/issue-labeler.txt

  apply-labels:
    name: Apply labels from Codex output
    needs: gather-labels
    if: ${{ needs.gather-labels.result != 'skipped' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    env:
      GH_TOKEN: ${{ github.token }}
      ISSUE_NUMBER: ${{ github.event.issue.number }}
      CODEX_OUTPUT: ${{ needs.gather-labels.outputs.codex_output }}
    steps:
      - name: Apply labels
        run: |
          output=${CODEX_OUTPUT//$'\r'/}
          if [ -z "$output" ]; then
            echo "Codex produced no output. Skipping label application."
            exit 0
          fi

          if ! printf '%s' "$output" | jq -e 'type == "array"' >/dev/null 2>&1; then
            echo "Codex output was not a JSON array. Raw output: $output"
            exit 0
          fi

          mapfile -t label_array < <(printf '%s' "$output" | jq -r '.[] | tostring')
          if [ "${#label_array[@]}" -eq 0 ]; then
            echo "Codex returned an empty array. Nothing to do."
            exit 0
          fi

          gh issue edit "$ISSUE_NUMBER" --add-label "${label_array[@]}" || true

      - name: Remove codex-label trigger
        if: ${{ always() && github.event.action == 'labeled' && github.event.label.name == 'codex-label' }}
        run: |
          gh issue edit "$ISSUE_NUMBER" --remove-label codex-label || true
          echo "Attempted to remove label: codex-label"
