name: nix-update-hash

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "pnpm-lock.yaml"

jobs:
  update-nix-hash:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for push access
      pull-requests: write # Needed for PR creation
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Need previous commit to check for changes
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@v8

      - name: Get if the pnpm-lock.yaml file has changed
        id: changed-pnpm-lock-yaml
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        with:
          # Avoid using single or double quotes for multiline patterns
          files: |
            pnpm-lock.yaml

      - name: Update nix pnpm hash on changed pnpm-lock.yaml file
        id: update-hash
        if: steps.changed-pnpm-lock-yaml.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-markdown-files.outputs.all_changed_files }}
        run: |
          nix run .\#update-nix-hash

      - name: Create branch
        if: steps.changed-pnpm-lock-yaml.outputs.any_changed == 'true'
        run: |
          git checkout -b update-npm-hash-$(date +%Y%m%d%H%M%S)
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add flake.nix
          git commit -m "Update npm hash in flake.nix"
          git push --set-upstream origin HEAD

      - name: Create Pull Request
        if: steps.changed-pnpm-lock-yaml.outputs.any_changed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update npm hash in flake.nix
          title: Update npm hash in flake.nix
          body: |
            This PR updates the npm hash in flake.nix based on changes to the pnpm-lock.yaml file.

            Automated PR created by GitHub Actions.
          branch: update-npm-hash-$(date +%Y%m%d%H%M%S)
          base: main
          draft: false

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        if: steps.changed-pnpm-lock-yaml.outputs.any_changed == 'true'
        with:
          message: |
            I have read the CLA Document and I hereby sign the CLA
